# Generated by Django 3.1.3 on 2021-01-26 15:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('clients_repayment', models.IntegerField(default=0)),
                ('lending_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('clients_name', models.CharField(max_length=200)),
                ('clients_id', models.CharField(max_length=200)),
                ('clients_phone', models.CharField(max_length=20)),
                ('borrowed_amount', models.IntegerField(default=0)),
                ('interest_charged', models.IntegerField(choices=[(0.15, 0.15), (0.05, 0.05), (0.075, 0.075)])),
                ('repayment_period', models.CharField(choices=[('1month', '1month'), ('2month', '2month'), ('3month', '3month')], max_length=100)),
                ('lender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
