# Generated by Django 3.1.3 on 2021-01-28 14:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('clients_loan_repayment', models.IntegerField(default=0)),
                ('repayment_day', models.CharField(blank=True, choices=[('mon', 'mon'), ('tue', 'tue'), ('wed', 'wed'), ('thur', 'thur'), ('fri', 'fri'), ('sat', 'sat'), ('sun', 'sun')], default='', max_length=200)),
                ('lending_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('clients_name', models.CharField(blank=True, max_length=200)),
                ('clients_id', models.CharField(blank=True, max_length=200)),
                ('clients_location', models.CharField(blank=True, default='', max_length=200)),
                ('mpesa_bank_ref', models.CharField(blank=True, default='', max_length=200)),
                ('clients_phone', models.CharField(blank=True, max_length=20)),
                ('loan_amount', models.IntegerField(default=0)),
                ('interest_charged', models.FloatField(default=0.0)),
                ('repayment_period', models.CharField(blank=True, choices=[('1month', '1month'), ('2months', '2months'), ('3months', '3months')], max_length=100)),
                ('office_expenses', models.IntegerField(default=0)),
                ('salary_expenses', models.IntegerField(default=0)),
                ('expense_description', models.CharField(blank=True, default='', max_length=100)),
                ('bad_debts', models.IntegerField(default=0)),
                ('mode_of_payment', models.CharField(blank=True, choices=[('cash', 'cash'), ('mpesa', 'mpesa'), ('bank', 'bank')], default='', max_length=100)),
                ('lender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month', models.CharField(choices=[('Jan', 'Jan'), ('Feb', 'Feb'), ('Mar', 'Mar'), ('Apr', 'Apr'), ('May', 'May'), ('June', 'June'), ('July', 'July'), ('Aug', 'Aug'), ('Sep', 'Sep'), ('Oct', 'Oct'), ('Nov', 'Nov'), ('Dec', 'Dec')], max_length=200)),
                ('total_payable_loans', models.IntegerField(default=0)),
                ('total_loans_given', models.IntegerField(default=0)),
                ('loan_repayments', models.IntegerField(default=0)),
                ('unrealized_interest_income', models.IntegerField(default=0)),
                ('bad_debts', models.IntegerField(default=0)),
                ('realized_interest_income', models.IntegerField(default=0)),
                ('office_expenses', models.IntegerField(default=0)),
                ('salary_expenses', models.IntegerField(default=0)),
                ('author', models.ForeignKey(blank=True, default='', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
