# Generated by Django 3.1.3 on 2021-01-30 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='installment_date',
            field=models.DateTimeField(verbose_name='date published'),
        ),
    ]
