# Generated by Django 3.1.3 on 2021-01-26 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0002_auto_20210126_1902'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='interest_charged',
            field=models.DecimalField(decimal_places=10, default=0.0, max_digits=19),
        ),
    ]
