# Generated by Django 3.1.3 on 2021-01-26 16:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0003_auto_20210126_1907'),
    ]

    operations = [
        migrations.RenameField(
            model_name='transaction',
            old_name='borrowed_amount',
            new_name='clients_loan_repayment',
        ),
        migrations.RenameField(
            model_name='transaction',
            old_name='clients_repayment',
            new_name='loan_amount',
        ),
    ]
