# Generated by Django 3.1.3 on 2021-01-27 07:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0005_auto_20210126_1927'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='clients_location',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='transaction',
            name='mpesa_bank_ref',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
    ]
