# Generated by Django 3.1.3 on 2021-01-27 08:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0006_auto_20210127_1058'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='repayment_period',
            field=models.CharField(choices=[('1month', '1month'), ('2months', '2months'), ('3months', '3months')], max_length=100),
        ),
    ]
