# Generated by Django 3.1.3 on 2021-01-27 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0007_auto_20210127_1104'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='interest_charged',
            field=models.DecimalField(decimal_places=0, default=0.0, max_digits=19),
        ),
    ]
