# Generated by Django 3.1.3 on 2021-01-27 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0009_auto_20210127_1126'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='repayment_day',
            field=models.CharField(choices=[('mon', 'mon'), ('tue', 'tue'), ('wed', 'wed'), ('thur', 'thur'), ('fri', 'fri'), ('sat', 'sat'), ('sun', 'sun')], default='', max_length=200),
        ),
    ]
