# Generated by Django 3.1.3 on 2021-01-27 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0010_transaction_repayment_day'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='bad_debts',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='transaction',
            name='office_expenses',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='transaction',
            name='salary_expenses',
            field=models.IntegerField(default=0),
        ),
    ]
